### ISSUE TITLE
error in common/spinlock.hpp

### ISSUE THREAD

**Issue by sandunder** [boostorg/sort#43]
in boost/sort/common/spinlock.hpp, line 72, here is a "not", because of this, it couldn`t compile successfully.

`    bool try_lock ( ) noexcept
    {
        return not af.test_and_set (std::memory_order_acquire);
    };
`

**Comment by Morwenn** [comment]
As a workaround your can `#include <ciso646>` before the Boost.Sort header, but that does sound like a problem worth fixing.

**Comment by sandunder** [comment]
It can fix the problem,thanks!

**Comment by fjtapia** [comment]
I am preparing the Windows Virtual Machine to install the last version of
Visual Studio and compile all again.

Visual C ++ is not intended to follow the C ++ standard, it is
intended to be followed by the C ++ standard. That makes them stupid
and annoying.

I compiled the code with GCC and CLANG, without any problems

But with Visual C ++ I had to include <ciso646> in a multitude of
files. From what I see, with the new versions, instead of going
forward, we go backwards.
Distinguishing yourself by stupidities is a sign of low intelligence,
and a strange way of gaining followers by making them waste their time
with stupidities.

I hope to have all resolved in one or two days. Thanks to all by your interest

Francisco

**Comment by fjtapia** [comment]
Please,
could you say me wich version of Visual C++ are you using ?

I just compiled with Visual Studio Community 2019. Version 16.6.5 and don't
have any error compiling the code.
Thanks

Francisco

**Comment by hendrikmuhs** [comment]
I can reproduce the problem, `#include <ciso646>` fixes it. As long as it is included somewhere before the boost includes, it fixes the problem. Nevertheless this is not a clean solution.

@fjtapia The reason why e.g. tests aren't affected: https://github.com/boostorg/sort/blob/develop/test/test_parallel_stable_sort.cpp#L13

To reproduce: change the include order or remove `#include <ciso646>` (requires some tests to be disabled or rewritten).

My env: Visual Studio Community 2019. Version 16.9.3
